spring:
  datasource:
    url: jdbc:mysql://8.133.170.159:3306/db2020?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: awnjqq58
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql