server:
  port: 9003
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 8.133.170.159:1111   #nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'

