server:
  port: 3344
spring:
  application:
    name: cloud-config-center   #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cf1429/springcloud-config.git    #github 上面的git仓库名字
          search-paths:
            - springcloud-config
          username: cf1429
          password: gt1429043932
      label: master    #读取分支
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka


