server:
  port: 3344
spring:
  application:
    name: cloud-config-center   #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cf1429/springcloud-config.git    #github 上面的git仓库名字
          search-paths:
            - springcloud-config
          username: cf1429
          password: gt1429043932
      label: master    #读取分支

  rabbitmq:
    host: 8.133.170.159
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#rabbitmq相关配置，暴露bus刷新配置的端点，curl -X POST http://localhost:3344/actuator/bus-refresh 全局通知
                                    # curl -X POST http://localhost:3344/actuator/bus-refresh/config-client:3355 定点通知，只通知3355这个服务
management:
  endpoints:   #暴露bus刷新配置的端点
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always





