server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 8.133.170.159:1111
    sentinel:
      transprort:
        dashboard: 8.133.170.159:8088
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: '*'


