server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://8.133.170.159:3306/db2020?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    username: root
    password: awnjqq58
    driver-class-name: com.mysql.jdbc.Driver



