server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://8.133.170.159:3306/db2020?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    username: root
    password: awnjqq58
    driver-class-name: com.mysql.jdbc.Driver

#配置日志,输出到控制台
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #逻辑删除配置
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
