server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由大的功能，利用微服务名称进行路由
          lower-case-service-id: true
      routes:
        - id: payment_routh
          #uri: http://localhost:8001/
          uri: lb://CLOUD-PAYMENT-SERVICE   #匹配后要提供服务的路由地址
          predicates:
            - Path=/payment/get/**

        - id: payment_routh2
          #uri: http://localhost:8001/
          uri: lb://CLOUD-PAYMENT-SERVICE    #匹配后要提供服务的路由地址
          predicates:
            - Path=/payment/lb/**
            - After=2021-02-13T10:36:54.290+08:00[Asia/Shanghai]   # 在此事后之后生效
            #- Before=2021-02-13T10:41:54.290+08:00[Asia/Shanghai]  #在此事件之前生效
            #- Between=2021-02-13T10:43:54.290+08:00[Asia/Shanghai],2021-02-13T10:44:54.290+08:00[Asia/Shanghai] #在这两个时间段以内有效
eureka:
  instance:
    hostname: cloud-geteway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-register: true
      defaultZone: http://eureka7001.com:7001/eureka

