spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.133.170.159:3306/db2020?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: awnjqq58

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.atguigu.springcloud.entity

