server:
  port: 83
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 8.133.170.159:1111 #连接通过nginx配置的nacos集群
        #server-addr: 8.133.170.159:8848   #连接单机nacos


service-url:
  nacos-user-service: http://nacos-payment-provider
