server:
  port: 83
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 8.133.170.159:8848


service-url:
  nacos-user-service: http://nacos-payment-provider
