server:
  port: 8005
spring:
  application:
    name: cloud-provider-payment
  cloud:
  #consul做为服务的注册中心
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

